<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ad_blog"
 *
 * Auto generated by Extension Builder 2013-04-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Blog system',
	'description' => 'An extbase / fluid based blog extension which includes a straight forward backend module',
	'category' => 'plugin',
	'author' => 'Adrian Dymorz',
	'author_email' => 't3@adrian.dymorz.ch',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>